name: "deploy"
description: "deploy action"

runs:
  using: "composite"
  steps:
    - name: Checkout current commit
      uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: "demo"
        path: dist

    - name: Setup Python 3.7 for awscli
      uses: actions/setup-python@v4
      with:
        version: '3.7'
        architecture: 'x64'

    - name: Install awscli
      shell: bash
      run: |
        pip install --upgrade pip awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::583388259455:role/from_github_aws_oidc_demo
        aws-region: ap-northeast-1

    - name: Get caller identity AWS
      shell: bash
      run: aws sts get-caller-identity

    - name: Uploading files
      shell: bash
      run: |
        aws s3 sync --delete dist ${{env.S3_BUCKET}} --cache-control max-age=60,s-maxage=60
    - name: Delete cf cache
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id ${{env.CF_DIST_ID}} --paths "/*"
