name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    tags:
      - dev-*

permissions:
  id-token: write
  contents: read

env:
  CF_DIST_ID: "EVED8FYT1CNCZ"
  S3_BUCKET: "s3://seminar-aws-s3-cloudfront-bucket"
  AWS_IAM: "583388259455"
  AWS_DEFAULT_REGION: "ap-northeast-1"
  BUILD_MODE: "dev"
  MATTERMOST_WEBHOOK_URL: "https://chat.teqnological.asia/hooks/7g7nycmbmt8q987wu4ykj3trke"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/deploy

  notify:
    needs: [build, deploy]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    steps:
      - name: Notify Mattermost on success
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ env.MATTERMOST_WEBHOOK_URL }}
          PAYLOAD: |
            {
              "attachments": [
                {
                  "color": "#00FF00",
                  "title": "Deployment succeeded",
                  "text": "Deployment succeeded"
                }
              ]
            }
      - name: Notify Mattermost on failure
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        continue-on-error: true
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ env.MATTERMOST_WEBHOOK_URL }}
          PAYLOAD: |
            {
              "attachments": [
                {
                  "color": "#FF0000",
                  "title": "Deployment failed",
                  "text": "Deployment failed"
                }
              ]
            }
