name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    tags:
      - dev-*

permissions:
  id-token: write
  contents: read

env:
  CF_DIST_ID: 'EVED8FYT1CNCZ'
  S3_BUCKET: 's3://seminar-aws-s3-cloudfront-bucket'
  AWS_IAM: '583388259455'
  AWS_DEFAULT_REGION: 'ap-northeast-1'
  BUILD_MODE: "dev"
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/deploy

